# Generated by Django 4.1.3 on 2022-11-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bert', models.IntegerField(default=0)),
                ('LSTM', models.IntegerField(default=0)),
            ],
        ),
    ]
